---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: prometheus-blackbox-exporter
    releaseName: blackbox-exporter
    repo: https://prometheus-community.github.io/helm-charts
    # renovate: registryUrl=https://prometheus-community.github.io/helm-charts
    version: 11.7.1
    namespace: monitoring
    valuesFile: ./values.yaml
