---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: renovate

resources:
  - sealed-secret.yaml

helmCharts:
  - name: renovate
    releaseName: renovate
    repo: https://docs.renovatebot.com/helm-charts
    # renovate: registryUrl=https://docs.renovatebot.com/helm-charts
    version: 46.26.2
    namespace: renovate
    valuesFile: ./values.yaml
