---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - manifests/namespace.yaml
  - manifests/configmap.yaml
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: mosquitto
      app.kubernetes.io/instance: mosquitto

images:
  - name: eclipse-mosquitto
    newName: eclipse-mosquitto
    # renovate: datasource=docker depName=eclipse-mosquitto
    newTag: "2.0.20"
