---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-automation

resources:
  - manifests/deployment.yaml
  - manifests/service.yaml
  - manifests/pvc.yaml

labels:
  - pairs:
      app.kubernetes.io/name: zwavejs2mqtt
      app.kubernetes.io/instance: zwavejs2mqtt

images:
  - name: zwavejs/zwavejs2mqtt
    newName: ghcr.io/zwave-js/zwave-js-ui
    # renovate: datasource=github-releases depName=zwave-js/zwave-js-ui
    newTag: "latest"
