---
# Values for robusta helm chart (unwrapped from umbrella chart)
clusterName: homeops
isSmallCluster: true
globalConfig:
  signing_key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#signing_key>
  account_id: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#account_id>
sinksConfig:
  - slack_sink:
      name: main_slack_sink
      slack_channel: monitoring
      api_key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#slack_sink_api_key>
  - robusta_sink:
      name: robusta_ui_sink
      token: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/46gjjkrum5jogfxzpejrrd6bam#robusta_sink_token>
enablePrometheusStack: false
enablePlatformPlaybooks: true
runner:
  sendAdditionalTelemetry: false
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "500m"
kubewatch:
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

customPlaybooks:
  - triggers:
      - on_pod_crash_loop:
          restart_reason: "CrashLoopBackOff"
    actions:
      - delete_pod:
          delete_options:
            grace_period_seconds: 0
            force: true
    name: delete_pod_on_crash_loop
