---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

helmCharts:
  - name: loki-stack
    releaseName: loki
    repo: https://grafana.github.io/helm-charts
    # renovate: registryUrl=https://grafana.github.io/helm-charts
    version: 2.10.3
    namespace: monitoring
    valuesFile: ./values.yaml

patches:
  - path: patch-sts.yaml
    target:
      kind: StatefulSet
