---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: agent-secrets
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: agent-job
spec:
  itemPath: "vaults/homelab/items/agent-secrets"
