---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: temporal-secrets
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: agent-worker
spec:
  itemPath: "vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3kozs35io74hobg7rdzjnsufju"
