---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: temporal
spec:
  encryptedData:
    .dockerconfigjson: AgCqrUuMC5CPoyllAHHmazUW0OMRnyL/KDh/LWDFgwIkJ2M1jEcwXqvGpR/mlSJO9wnbyC9po44z7POYKK8yIA3/2GISXIx8fzcJ/qYX6bIgq548L5M+pG2SfOtXEPD5tMpWqEYfsR8IsoTz8aOEqFL9a/y0zsR6BuNo8dlEmBHAHDagP+dKOHtG+tiKnDWDXr6NBPWJNM6APCxJW8gXkNluSe6Mhwk5cQAm7/i02vNpHMma5PzBFbuk14Df364QpXkXDjg5m3VU4ueZFYRJqnxOwR+VE+WnkPvxTvhgbVaUeldkqH+WFohUWhdpfRfdd4+22w/7j166RgbxZj/dMv1YkfkngTML4zrU6A96B32hbMdICaylqdK6bgpP0hZ1hEf+1370AKqO2vJjfLFc46y+2qqOdYbtFN23IcpZGlOsRLlvIfL56a7kFc7CXo75e0kR+dq7xm5wh7BexH+1G/mya4tANqM02V6fsXwegmgh4djbAuZBSxqNEtPlb31eRQlRyEbcSZ2GgGkQTIsQJfgI2d7sBCfutGA3PB/+Gjv4MI7I3SjnCoIlqJ98vMrtWnKRDYJ5KHHT7ES4F2130EE+krGvAPqRMdeIIFvhbVJyehJCCWk6LtKyknEZ/ns+XnKB8BSARtkEAXOGniUolF+8MSpFzDYVE9fqAk10419XUnWUUauGcCRRQhChCz9Axh+pqiQVK40Bq/1o3seUoPVZzWkNik/CFtUDMdamRWdGEHjY0YZQwD4YISbB8DPGfuan97YKQ/3TUDYAqZhXqqITJrUvsDewY2wKN1tkrjOXCNd3CpoahVOOxWeZc+dqRSTaxmWCxlLHQmCtMu0dCML1hEk+wSGTkYCbJ5r62TMjLLvWcNPnNjaAMGa84SnR0Ig/NcUT+hgL7vmXSf1mX5VjUHQhpBMl6BGVDoYH2Vxze0oN02KbjNe3Yi9Rvro6QSa96dgFMPccEA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: temporal
    type: kubernetes.io/dockerconfigjson
