---
apiVersion: v1
kind: Secret
metadata:
  name: github-app
  namespace: temporal
  labels:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: agent-worker
type: Opaque
stringData:
  github-app-id: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3kozs35io74hobg7rdzjnsufju#github-app-id>
  github-installation-id: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3kozs35io74hobg7rdzjnsufju#github-installation-id>
  github-app-private-key: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3kozs35io74hobg7rdzjnsufju#github-app-private-key>
  github-webhook-secret: <path:vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/3kozs35io74hobg7rdzjnsufju#github-webhook-secret>
