---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - manifests/namespace.yaml
  - manifests/ingress.yaml
  # Uncomment after creating sealedsecret-encryption.yaml:
  # - manifests/sealedsecret-encryption.yaml

helmCharts:
  - name: n8n
    releaseName: "n8n"
    repo: https://8gears.container-registry.com/chartrepo/library
    version: 0.24.0
    namespace: automation
    includeCRDs: true
    valuesFile: ./values.yaml

labels:
  - pairs:
      app.kubernetes.io/name: n8n
      app.kubernetes.io/instance: n8n
