---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - manifests/ingress.yaml
  - manifests/sealedsecret-encryption.yaml
  - manifests/pv-pvc.yaml

helmCharts:
  - name: n8n
    releaseName: "n8n"
    repo: oci://8gears.container-registry.com/library
    version: 2.0.1
    namespace: automation
    includeCRDs: true
    valuesFile: ./values.yaml

labels:
  - pairs:
      app.kubernetes.io/name: n8n
      app.kubernetes.io/instance: n8n

images:
  - name: n8nio/n8n
    newName: n8nio/n8n
    # renovate: datasource=docker depName=n8nio/n8n
    newTag: "2.4.4"
