---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: agent-secrets
  namespace: automation
spec:
  encryptedData:
    ANTHROPIC_API_KEY: AgCAm89IXoYaFdYprbgKPltxjN64YnguFLZTEVPqiYlPKoqiEFoLPINrr67bbZDgPfXmPuumKYsySv92CR8QavNIr93nlVTJaKLYVKTv8yg/LY+YxtsFYySm+Xwb3+SbRNAfdSawudG7owZHja1XGrH8KOhlzdMBhx/Z8pvL4mdBKrsGYpbR/srta8CXeBOIs9wpzMfOZQi/QAkkcRQNNy0zkAZsR4M/26wqTtVDdjkz2fRbcjy4qKtVni6UX/Qa47sE846PabY3VDNlwXd96ybAa9A9g29GM4ksh7CEymqhPfBEhl6MlcSE968T9lTsbEszwppGQJ8vY40xddYVGLnZGUVBk6SSlsYBg0hNnesTLlSLCecM261nefOMpuzOS6lWEZvFsygpKpKQAXbJ6kG3WD0i170h6Ao5ORYpiZFE3O+tSJESVESniTN3ASVd1ULnsLqOM4+H1zKF7DGKm00DYMDZD2kfHnBQHTnhVTfh77wdvperyCyvIytmdFtq5Bz2OxJMN/JrR50081AdAOBj1MXdA4YOMYrjkLhiuxplE3ZDoarISiqfCmeQSG/GJta2ta1VgoA6NIzN2v2c7+jL4tPR89WY4LcuJQv3aiYIH1xu0v3Fngx4ghEYHxTDO1xl5CL8qyVxDv2L52/c7VbwUBq311mTdNyy/e1bodwH9ncanW3gkeLg//wys1raS07vYhvjL8V9MRqzyRwzHdO8ZJHRbqTW1XjIfQlc8SQYmSMtUTcxOaiByhKqfM8EC6aOyOqITab2NW1bkqbbzWh/xXeNHZEDJq0GzCTviQyoVDe6EHoqcTxjb18rKxQZ8O6GY6wGj8vzRQL4Tvs=
  template:
    metadata:
      name: agent-secrets
      namespace: automation
    type: Opaque
