---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: automation
spec:
  encryptedData:
    db-password: AgAL97RGbaMmzec3BKRQXN9AqdqeyZ0l8RZLIeMxJAd+l23COL5jm40otUuEC/Qki95TmUbi36s5hEUcklBw44pFuMef3dG1QD+OEoUcMESdw4dyBFbanWll0crtQHMjylblw58nrcBhJOEosv0zCfbKH4lG9PdmL27BxAbB9XTgxvKNHuVbBLfc73F90aN69XWPzP/0Iq0KxYz2JY2LatvBciq3JGmw3dZEY3EkmoW65QlCgPYXslVCbTsrpFsDqaqhA23/dEhn8HERuOC7+fK/GG7C/7yxmxERL238TviofagVSol6iR3fqJVp5OhehcjPexXO49rUMbrsy+hTVQ4vTUqfICyGwq/9JJZro4iOJZFq+9665GKclZ4v9rtPYUsxKwPW2C2QhcQUtmwWOE85fQpWpGV6X5hQGWG61B1Mf+eZo2ydTbMuNfyrqq2xwsDCbzllFcaNmgDsnP2HoxSzm3Q2ulXGZHLLLgXwTIVqYqGX/2GSDzOA4ivz1nUmfc+hmj306nMq9XtxtfpAnfBPOLPZSSlRD25jxPwuGtYYFQmTmcs6YzaeosoI0tsSx19XhmMtG2jEOS6EA7DgTIPKCZk968WxrEN7lOq1EHOvYowMjL8TvBo6iK4w/yh9keVco2PGZpw5BAFQXlsK27t3M0xEel5FQdWqi7xCkL9u2QmD9qrjd1qD3KFoW8TIIS7+Fva2bpmHDVxKaVEhgD0he50t3fbvvA4MPHGtllXORobIrV/ZURSCO4MD
    encryption-key: AgArXRM4l7F9T7CCYU1J2yHniQ8vzfkaExOhlFpprXHoT0fzLUPmAqTiHt979h1bHT2uqVxMi9xj4gvW8/Mts7J7gcLvUFbThVDwpL+igd21fgPlJ8IK63up8RQPeIBaGGHCe6Zf/QiCfSd2iZ8/+W6DJN2wx0VSRu7irjObJMhxtpnsKxBc49OZqTrW9wfIp/g204L8XMth1lOqLX/QubaKwI9h/hzH5RLKmYXIHHKTe+k4qKeWdAMUej9ASHEt5x0iQlJSUqStytJCnnQNp4OpNvxKLJfHxQvhTn2r6bZrJLVpXixuxxqON5kdaNDd4JtD9ShkGQTK/Otr4fPg2dmyw+6sAgDVFmnTh9GwqzJPKoEY2c/tsmcGXLcXu7oFepgx8LF2akAbVWX9Ygq3j0uUJRWqY5LstnOfB5zT8NgaeqwYAIB1Mvac2hXLtgYb4BoeygRXzQuQdc5ARFLiU5Zd/smtfE6qLx7YyRdDZnCGznWWC3ZpHgmnIDRYDinWi1uJBRnPB17Fm/Sf4Vut88kBFuC98Kjh2dYDeN5KpGG5me+lFZTJXDNeNZkJnwh3YLXpVLtmatRydmWrQ0tRM9RZgYMnnKHwKlZSBzx9eugYotOscuC994XJ7mwSW6+kE0BZKcew/VgB9qv4HgXQWXnqV5rUUMxUCOrLTM3EuYmZNIYzmJcnz03k50vSrwKSO9b9ufFKU1pB1GYujh9tdO6eVTPtkXTqCHv5kdhtqJSBnyRfpMXS1fb6nNC7nw==
  template:
    metadata:
      name: n8n-secrets
      namespace: automation
