---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: n8n-secrets
  namespace: automation
spec:
  encryptedData:
    db-password: AgAsTcKVnnXokzAVejzQpEhSjfNknDrYfVKdwoKtQV6+pFO7ZU/SzeVWl6aD7O3FiZOLZoXSUympYJUQ8Jc9KZ8jCNMlf5t2kBAsFReFdP+vKLgJ59xYAwrKn8JcCQodoIxhh5eMoQOuUm1QdR7t5prbSsgv5Bfd4zjOBz4Eydu4+Odv1C4mKmhjqFRk0EG5nrQy6T19mjgtr6lquxeUf6voQH+E239jdjsqSOQZOjCUprQ5QTWNc7DmXU8VEb5gM9GjIil/SDgkOWhaH2OuKs0yFX73KXdd7O2tsdijoyPdZ+xHjm9vSo5Q60c8iy0brwQpX+YvTDBnmiEbMejCdPK7ipxw+h4egrbnDdfxv7TCex3IpxcSF+xn0UQP8OEQ+/txEJIFZFWJh+bkB/UdinwNAsC7sGUF4eas3IwBuVHmc7uOBicmkajWshJTiqniG+44i95l1ddhmV+0PngGl2z9JVYVMQ6kp3ujTqZAPLiM8EqEBMUHCPvZzDW36v8CroWdpIVRGLJYCdlh95TwrZ5/NlTXewUqOCt/0IO8rDmbFPbQ+JR7wCXVcEvSbITHGnaIqUAjFeePcX0yf51meuLzYT/t+/ywmigLs1C69L1mGiaQGFlt2cHOSF6xyr9iJY2ol6nR8QTau+HdJXDVRs8fS9EqTzwT3T5kwUbS1mJ9usfRr9+5NwqIFUKAntakdQD7y3/Syyxv12yn7YMkkJX03oCkyoBZ8VUdF3bVb635qnsCA0zHDYBSEW0CgA==
    encryption-key: AgB4eUT6VSsqk5QskFwEizXTQkwYQTpSPM3EdEefKwCDtjHDFk921aZNRDAXev3J5M6icAHSCL71I/GhDFG8GWl7QyCTOGzp3ZGsgD5Tvv1xJwK5cuhTSqwYJwNIHSjDAckwldZBuIOYHQCkg9i825hsLGc20VQ+lGFHZrhmSQ/NKYElQgRfb6mTzD4MatKDgsX8It1RU+JhcWIlfutdHkpUh/jnKq5D8l2VYsg/YKFH3FUcSdiMYFjrHV1Ugp39Sa44vIPhKmqVnisDHtr6UHWDJ/j301xs1Ps/lqNai6cCtZ09ndgyDxyGdn+OOyPEvz3optTVyktE9ilRL7VgAC8OPDVrwzah2mpIyTfRrsW+IZorRnOox0874jbi5m5cOuWaLes85bicGyEtDq27EYo3aESj0PhFk5v7zwwpn+ZuZT2/oI9wkFZ2AfkTl+c9SyEqQKD7/xYdSsP+2shcvq13QN1nuwLvt7tFKZhGS+qmRAZJNvxtWzYA77ycR3I6lFiDUS5s3zr/LfK+BorE1RVhBFtugC4NLWSOEQm1AeeSgpcEsoSmWNBOymRWsjNB0CEnTQtDq+6kzZ76fUUYNYJ5WWl+H8RPgGifH7CP4o/cxovlsgr7+0UqPRMfvgEe8SHtRhmU1zJQ1TzGk3kp3+TPmpP5IQYv72t+67S20/+1KWj/vSoJVOUqIkcsxvusou7TmsXBgVCPWB23tuN7vO7uPuyOGBChvUH0Tmdq0HTQK7mkGXS6kXVG53tbGg==
  template:
    metadata:
      name: n8n-secrets
      namespace: automation
    type: Opaque
