---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: automation

resources:
  - manifests/configmap-init.yaml
  - manifests/statefulset.yaml
  - manifests/service.yaml
  - manifests/sealedsecret-credentials.yaml

labels:
  - pairs:
      app.kubernetes.io/name: postgresql
      app.kubernetes.io/instance: postgresql

images:
  - name: postgres
    newName: postgres
    # renovate: datasource=docker depName=postgres
    newTag: "18-alpine"
