---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: automation
spec:
  encryptedData:
    .dockerconfigjson: AgA4Y4OLb03a1jN8cIQSR83Tl8fm1zWyzdN0GTAXmzFSyTb2i6HydH9kDD2PDm7jm9NuI6+0vrS3fu48r8mwCDA8Og/FpRd4TJ4XXpsjS01+jeP7wuceLGPuspvtiBX0Sdy2wvJkUkM0YqTEdZhs/dY5ujPRpIUjGm8FGLctZqyq2me9udx8j8ATef7JWk/21X2W7SUoj2VeXsE9hPiRMqH4UIcHVenxMAHEe9LvVdDSjrSkC7ukk8vOQ/yN2kaLnn10WFvG7D87TrhFbStAdM2aKwjJvAOb3oMzXmRRLo0tiTbXz05SuV+hlpJBbB6FJfiAAAnpfHLIHwNzl3WPMowOjDBnGkYLfALA6Gy2xr5X3jRIcXC4zgPcMY/XCuDfDQTLtJygQ+65SHHXOCH1N+Nky7TxZwSFe46yqw5J1JCDyOLSqyQQheiadjM6nDWyFYrscmYniY3nhizagIHZxKiL0/pfTvjQjLE0Er+67IRdCVrcSShOijyGpFXdesdLiLaeRD7aUHPQ4RTMauqzjaWHpV9vIswfpovhM+H2SJ66YlA9FPWvcOUeAbW5Y1EY11UJEa3mIolZ4qjqv9Ir541eyFd2RPesHyURKCkRvS2leKlPY4ces/kaBoQyXUiGpGNxMz5Hi1VIwvlNdPouYQBVo6aulaOkeFatRClmEWCCI+UlEV/SN/0OPoRpGgw4dAHtTNpVtPuI/QdiLSUVhatZUCEE2pcpht9GhwqWXRmc4pVCCYuW7ENNzFHfnrRmyZDgjIdxNfhjbkWbbIexykMTwx/TvPgZOioeUvfvPm9MYucStL5T3A+cgb/4Mjde/Xv6OCDYVL6Yh+kZalNQvMve+W/Po+LfHRN9B7sWZteJF+BSrr/F7E8XrbPj10tJmH+MccZEiBAcVsCb2rngJlz0mwO0fO7H6kVr0OtvHBLZbKCfybUbiCUYXm6Iabb7tqiHVyO+bpun/Q==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: automation
    type: kubernetes.io/dockerconfigjson
