apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: ghcr-pull-secret
  namespace: focus-ai
  labels:
    app.kubernetes.io/name: focus-ai
type: kubernetes.io/dockerconfigjson
spec:
  itemPath: "vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/lgxw6ywr3j7tqz22n5tnhk7rmu"
