apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: postgres-credentials
  namespace: focus-ai
  labels:
    app.kubernetes.io/name: focus-ai
    app.kubernetes.io/component: database
spec:
  itemPath: "vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/27lfiocjcf2rofme5ui3osycym"
