apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: focus-ai-secrets
  namespace: focus-ai
  labels:
    app.kubernetes.io/name: focus-ai
    app.kubernetes.io/component: api
spec:
  itemPath: "vaults/mfjan54l7fzgdzlykwb2b6nj3a/items/cctz254gihjzbdzqtkff2vdldy"
