---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - sealed-1password-credentials.yaml
  - sealed-op-token.yaml

helmCharts:
  - name: connect
    releaseName: connect
    #  repository: https://1password.github.io/connect-helm-charts/ # their helm repo is down atm
    repo: https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
    # renovate: registryUrl=https://raw.githubusercontent.com/1Password/connect-helm-charts/gh-pages/
    version: 2.3.0
    namespace: default
    valuesFile: ./values.yaml
