---
connect:
  credentialsName: op-credentials
  credentialsKey: 1password-credentials.json
# install the operator
operator:
  create: true
  authMethod: service-account
  serviceAccountToken:
    name: op-token
    key: token
