---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ring-mqtt-config
  namespace: home-automation
data:
  config.json: |
    {
      "mqtt_url": "mqtt://mosquitto.home-automation.svc.cluster.local:1883",
      "enable_cameras": true,
      "snapshot_mode": "all",
      "enable_modes": true,
      "enable_panic": false,
      "beam_duration": 30,
      "disarm_code": "",
      "location_ids": []
    }
