---
apiVersion: v1
kind: Service
metadata:
  name: ring-mqtt
  namespace: home-automation
  labels:
    app.kubernetes.io/name: ring-mqtt
    app.kubernetes.io/instance: ring-mqtt
spec:
  type: ClusterIP
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
      protocol: TCP
    - name: http
      port: 55123
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: ring-mqtt
    app.kubernetes.io/instance: ring-mqtt
