---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: sealed-secrets
    releaseName: sealed-secrets
    repo: https://bitnami-labs.github.io/sealed-secrets
    # renovate: registryUrl=https://bitnami-labs.github.io/sealed-secrets
    version: 2.18.0
    namespace: kube-system
